In [1]:
pip install numpy


In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [5]:
arr_2=np.array([[1,2,3],[2,4,5]])
print(arr_2)

[[1 2 3]
 [2 4 5]]


In [9]:
arr_3=np.array([[1,2,3],[4,5,6],[9,8,0]])
print(arr_3)

[[1 2 3]
 [4 5 6]
 [9 8 0]]


In [36]:
arr=np.array([1,2,3])
print(arr)
print("diminsions is",arr.ndim)
arr_2=np.array([[1,2,3],[2,4,5]])
print(arr_2)
print("diminsions is",arr_2.ndim)
arr_3=np.array([[1,2,3],[4,5,6],[9,8,0]])
print(arr_3)
print("diminsions is",arr_3.ndim)

[1 2 3]
diminsions is 1
[[1 2 3]
 [2 4 5]]
diminsions is 2
[[1 2 3]
 [4 5 6]
 [9 8 0]]
diminsions is 2


In [17]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
one=np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
random=np.random.random((3,3))
print(random)

[[0.78598737 0.09495168 0.85784965]
 [0.7370472  0.95910382 0.62763906]
 [0.11449882 0.57307501 0.90627219]]


In [30]:

#arange
arrange=np.arange(1,10,2)#start,stop,step
print(arrange)

[1 3 5 7 9]


In [32]:
#identity
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#array attributes
arr=np.array([[1,2,3],[2,5,6]])
print("shape",arr.shape)
print("size of array",arr.size)
print("data type",arr.dtype)
print("number of dimensions",arr.ndim)
print(type(arr))

shape (2, 3)
size of array 6
data type int64
number of dimensions 2
<class 'numpy.ndarray'>


In [40]:

'''Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.'''

temp_data=np.array([[22,25,20],[24,26,20]])
print(temp_data)
print("shape",temp_data.shape)
print("size of array",temp_data.size)
print("data type",temp_data.dtype)
print("number of dimensions",temp_data.ndim)
arr_3=np.array([[21,23,22],[22,25,20],[24,26,20]])
updated_temp_data = np.concatenate((temp_data, arr_3))
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print("updated_temp_data\n",updated_temp_data)
print("sensor_error_flags\n",sensor_error_flags)
print("greenhouse_identity\n",greenhouse_identity)




[[22 25 20]
 [24 26 20]]
shape (2, 3)
size of array 6
data type int64
number of dimensions 2
updated_temp_data
 [[22 25 20]
 [24 26 20]
 [21 23 22]
 [22 25 20]
 [24 26 20]]
sensor_error_flags
 [[0. 0. 0.]
 [0. 0. 0.]]
greenhouse_identity
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
arr=np.array([1,2,3])
print(arr[1])
arr_1=np.array([[[1,2,3],[2,6,7]],[[1,4,6],[5,7,8]]])
print(arr_1)
print(arr_1.ndim)
print(arr_1[1,1,1])
print(arr[-1:])

2
[[[1 2 3]
  [2 6 7]]

 [[1 4 6]
  [5 7 8]]]
3
7
[3]


In [64]:
'''Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.'''

fruits=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
shipments=np.array(fruits)
print(shipments)
print(shipments[1,1])
print("number of apples shipped on wednesday",shipments[0,2])
print("number of oranges on sunday",shipments[1,0])
print("multiple elements accessing",shipments[0,0:6])
print("fruits from mon-fri",shipments[:,0:6])
print("only weekend",shipments[:,5:7])
print("shipping apples from wednesdat to saturday",shipments[0,2:6])
shipments[0,5]=100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
45
number of apples shipped on wednesday 55
number of oranges on sunday 40
multiple elements accessing [50 60 55 70 65 80]
fruits from mon-fri [[50 60 55 70 65 80]
 [40 45 50 60 55 70]]
only weekend [[80 90]
 [70 75]]
shipping apples from wednesdat to saturday [55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [69]:
#arithmetic operations
a=np.array([4,9,25])
b=np.array([9,8,7])
print(a+b)
print(a-b)
print(a*b)
print(a*2)
print(np.dot(a,b))#matrix multiplication
#broadcast
c=np.array([90,3,8])
d=2
print(c+d)
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.prod(a))


[13 17 32]
[-5  1 18]
[ 36  72 175]
[ 8 18 50]
283
[92  5 10]
[5.45981500e+01 8.10308393e+03 7.20048993e+10]
[2. 3. 5.]
[1.38629436 2.19722458 3.21887582]
4
25
12.666666666666666
8.9566858950296
80.22222222222221
38
900


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [91]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])


production_all=np.stack((farmA,farmB,farmC),axis=0)


print(production_all)
print(production_all.ndim)
print(production_all.shape)
print(production_all.size)
print(production_all.dtype)

total_per_farm=np.sum((production_all),axis=(1,2))
print("total energy per farm",total_per_farm)
var=np.var((production_all),axis=(1,2))
print("variance per farm",+var)
mean=np.mean((production_all),axis=(1,2))
print("mean per farm",+mean)
std=np.std((production_all),axis=(1,2))
print("standard deviation per farm",+std)

hour_weights=np.array([0.5, 1.0, 0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print(weighted_per_panel)


production_all = np.stack((farmA, farmB, farmC), axis=0).astype(float)



production_all[1] += 0.5
print("\nFarm B adjusted (first 2 rows):\n", production_all[1][:2])




norm_data = (production_all - mean[:, None, None]) / std[:, None, None]
print("\nNormalized data shape:", norm_data.shape)


exp_data = np.exp(norm_data)
log_data = np.log(np.abs(norm_data) + 1)
sin_data = np.sin(norm_data)
round_data = np.round(norm_data)
floor_data = np.floor(norm_data)
ceil_data = np.ceil(norm_data)
print("\nexp_data shape:", exp_data.shape)


high_output = production_all > 20
even_hours_mask = (np.arange(3) % 2 == 0)[None, None, :]
combined_mask = np.logical_and(high_output, even_hours_mask)
print("\nHigh output mask shape:", high_output.shape)


alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],

    [[1,1,0],
     [0,1,1],
     [1,0,1],
     [0,1,0]],

    [[0,1,0],
     [1,0,1],
     [1,1,1],
     [0,0,1]]
], dtype=int)

bit_and = np.bitwise_and(alerts, (production_all > 15))
bit_or = np.bitwise_or(alerts, (production_all > 15))
print("\nBitwise AND example:\n", bit_and[0])



added = np.add(production_all, 2)
subtracted = np.subtract(production_all, 1)
multiplied = np.multiply(production_all, 2)
divided = np.divide(production_all, 2)
powered = np.power(production_all, 2)
modded = np.mod(production_all, 5)
print("\nArithmetic examples done.")


print("\nSum(exp(norm)):", np.sum(np.exp(norm_data)))
print("Mean(sin(norm)):", np.mean(np.sin(norm_data)))



panel_totals_per_farm = np.sum(production_all, axis=2)  # (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)



overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=(0,2))

print("\nOverall total energy:", overall_total)
print("Peak value:", peak_value, "at (farm, panel, hour):", peak_index)
print("Average per panel across farms:", average_per_panel)










[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
3
(3, 4, 3)
36
int64
total energy per farm [126 234 174]
variance per farm [3.91666667 3.91666667 3.91666667]
mean per farm [10.5 19.5 14.5]
standard deviation per farm [1.97905701 1.97905701 1.97905701]
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

Farm B adjusted (first 2 rows):
 [[20.5 19.5 21.5]
 [18.5 20.5 19.5]]

Normalized data shape: (3, 4, 3)

exp_data shape: (3, 4, 3)

High output mask shape: (3, 4, 3)

Bitwise AND example:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Arithmetic examples done.

Sum(exp(norm)): 63.071430863729034
Mean(sin(norm)): 0.04853967380227196

Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs maintenance: [ True False  True]

Overall total energy: 540.0
Peak value: 23.5 at (farm, panel, hour): (np.int64(1), np.int6

In [95]:
arr=np.array([1,2,3,4,5,6,7,8,9])
reshape=arr.reshape(3,3)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [123]:
#vertical stack
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("vertical",np.vstack((a,b)))
print("horizantal",np.hstack((a,b)))

#split into three parts
c=np.array([1,2,3,4,5,6,7])
print(np.array_split(c,6))

#advance indexinggg
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
#fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])


#copy vs view  ------view shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)

#copy doesnt share memory
copy=arr.copy()
copy[0]=10
print(arr)

#save to a file
arr=np.array([1,2,3])
np.save('array.npy',arr)
#load from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)


vertical [[1 2 3 4]
 [5 6 7 8]]
horizantal [1 2 3 4 5 6 7 8]
[array([1, 2]), array([3]), array([4]), array([5]), array([6]), array([7])]
[4 5]
[10 30]
[10  2  3]
[10  2  3]
[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [182]:
#arange
arr=np.arange(1,51,1)#start,stop,step
print(arr)

r=np.random.rand(3,3)
print(r)
#Array Attributes
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)
#Basic Operations
print(5+arr)
a=np.array([1,2,3])
b=np.array([2,3,4])

#Indexing and Slicing
arr1=np.arange(1,26,1)
shape=arr1.reshape(5,5)
print(shape)
print(shape[0,:])
print(shape[:,-1])
print("rows cols",shape[:3,:2])
#Aggregation

# Random integers between 10 and 100, size 10
arr = np.random.randint(10, 101, size=10)
print("Random array:", arr)
print("max values of arr",np.max(arr))
print("min values of arr",np.min(arr))
print("standard deviation values of arr",np.std(arr))
print("variance values of arr",np.var(arr))

#Reshaping
arr=np.arange(1,13,1)
shape=arr.reshape(3,4)
print(shape)

#Broadcasting
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr.reshape(3,3)
arr2=np.array([1,2,3])
print("sum of",arr1+arr2)

#Filtering
arr3=np.random.randint(1,50,50)
print(arr3)
print("elements divisible by 5",arr3[arr3%5==0])

#Matrix Multiplication
a=np.array([[2,3],[3,4]])
b=np.array([[2,3],[4,0]])
print("multiplication",np.dot(a,b))

import numpy as np

arr = np.arange(1,13,1)
shape = arr.reshape(3,4)
print("2D array:\n", shape)


indices = np.arange(shape.shape[0])  # [0,1,2]


diagonal_elements = shape[indices, indices]
print("Diagonal elements:", diagonal_elements)






[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[0.62887373 0.80281506 0.53434844]
 [0.51317446 0.51365589 0.11250017]
 [0.57984538 0.87733668 0.09366049]]
1
(50,)
int64
50
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
rows cols [[ 1  2]
 [ 6  7]
 [11 12]]
Random array: [44 97 80 89 54 17 46 16 45 77]
max values of arr 97
min values of arr 16
standard deviation values of arr 26.971281022598834
variance values of arr 727.45
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum of [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[ 1 20 25 25 49 35 27 23 20 12 12 30 21 43 30  2 33 17 48 19 28 32 14  2
 29 27 20 37 34 25 39 36 43 27  4 20 22 11 19  4 17 29 29 23  3 16 11  4
 4